### ISSUE TITLE
ImportError: No module named soft_dtw_fast

### ISSUE THREAD

**Issue by Deruijter** [mblondel/soft-dtw#3]
I've installed the program as mentioned:

```
git clone https://github.com/mblondel/soft-dtw.git
pip install numpy scipy scikit-learn cython nose
cd soft-dtw
make cython
python setup.py build
sudo python setup.py install
```

I have also added the soft-dtw folder to PYTHONPATH

When I open a new python session and try to do `from sdtw import SoftDTW` I get the following error:

```
>>> from sdtw import SoftDTW
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/leven/Applications/soft-dtw/soft-dtw/sdtw/__init__.py", line 1, in <module>
    from .soft_dtw import SoftDTW
  File "/home/leven/Applications/soft-dtw/soft-dtw/sdtw/soft_dtw.py", line 6, in <module>
    from .soft_dtw_fast import _soft_dtw
ImportError: No module named soft_dtw_fast
```

Could it be that I'm missing a certain step during the installation?

**Comment by mblondel** [comment]
Any error message in one of these steps:
```
make cython
python setup.py build
sudo python setup.py install
```
?

**Comment by Deruijter** [comment]
Thank you for your quick reply.

There don't seem to be any errors, only a warning when performing python setup.py. build.
Note that I'm using python 2.7.11 with anaconda by the way.

Here's the output of the three commands you mentioned:
```
(python27) $ make cython
cython sdtw/soft_dtw_fast.pyx
```

```
(python27) $ python setup.py build
Warning: Assuming default configuration (sdtw/tests/{setup_tests,setup}.py was not found)Appending sdtw.tests configuration to sdtw
Ignoring attempt to set 'name' (from 'sdtw' to 'sdtw.tests')
Appending sdtw configuration to 
Ignoring attempt to set 'name' (from '' to 'sdtw')
running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
build_src
building extension "sdtw.soft_dtw_fast" sources
build_src: building npy-pkg config files
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/sdtw
copying sdtw/distance.py -> build/lib.linux-x86_64-2.7/sdtw
copying sdtw/dataset.py -> build/lib.linux-x86_64-2.7/sdtw
copying sdtw/path.py -> build/lib.linux-x86_64-2.7/sdtw
copying sdtw/barycenter.py -> build/lib.linux-x86_64-2.7/sdtw
copying sdtw/__init__.py -> build/lib.linux-x86_64-2.7/sdtw
copying sdtw/chainer_func.py -> build/lib.linux-x86_64-2.7/sdtw
copying sdtw/setup.py -> build/lib.linux-x86_64-2.7/sdtw
copying sdtw/soft_dtw.py -> build/lib.linux-x86_64-2.7/sdtw
running build_ext
customize UnixCCompiler
customize UnixCCompiler using build_ext
building 'sdtw.soft_dtw_fast' extension
compiling C sources
C compiler: gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC

creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/sdtw
compile options: '-I/home/leven/Applications/anaconda2/envs/python27/lib/python2.7/site-packages/numpy/core/include -I/home/leven/Applications/anaconda2/envs/python27/lib/python2.7/site-packages/numpy/core/include -I/home/leven/Applications/anaconda2/envs/python27/include/python2.7 -c'
gcc: sdtw/soft_dtw_fast.c
In file included from /home/leven/Applications/anaconda2/envs/python27/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1809:0,
                 from /home/leven/Applications/anaconda2/envs/python27/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /home/leven/Applications/anaconda2/envs/python27/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from sdtw/soft_dtw_fast.c:517:
/home/leven/Applications/anaconda2/envs/python27/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
gcc -pthread -shared -L/home/leven/Applications/anaconda2/envs/python27/lib -Wl,-rpath=/home/leven/Applications/anaconda2/envs/python27/lib,--no-as-needed build/temp.linux-x86_64-2.7/sdtw/soft_dtw_fast.o -L/home/leven/Applications/anaconda2/envs/python27/lib -lpython2.7 -o build/lib.linux-x86_64-2.7/sdtw/soft_dtw_fast.so
```

```
(python27) $ sudo python setup.py install
Warning: Assuming default configuration (sdtw/tests/{setup_tests,setup}.py was not found)Appending sdtw.tests configuration to sdtw
Ignoring attempt to set 'name' (from 'sdtw' to 'sdtw.tests')
Appending sdtw configuration to 
Ignoring attempt to set 'name' (from '' to 'sdtw')
running install
running bdist_egg
running egg_info
running build_src
build_src
building extension "sdtw.soft_dtw_fast" sources
build_src: building npy-pkg config files
creating soft_dtw.egg-info
writing soft_dtw.egg-info/PKG-INFO
writing top-level names to soft_dtw.egg-info/top_level.txt
writing dependency_links to soft_dtw.egg-info/dependency_links.txt
writing manifest file 'soft_dtw.egg-info/SOURCES.txt'
reading manifest file 'soft_dtw.egg-info/SOURCES.txt'
writing manifest file 'soft_dtw.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
customize UnixCCompiler
customize UnixCCompiler using build_ext
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/sdtw
copying build/lib.linux-x86_64-2.7/sdtw/soft_dtw_fast.so -> build/bdist.linux-x86_64/egg/sdtw
copying build/lib.linux-x86_64-2.7/sdtw/distance.py -> build/bdist.linux-x86_64/egg/sdtw
copying build/lib.linux-x86_64-2.7/sdtw/dataset.py -> build/bdist.linux-x86_64/egg/sdtw
copying build/lib.linux-x86_64-2.7/sdtw/path.py -> build/bdist.linux-x86_64/egg/sdtw
copying build/lib.linux-x86_64-2.7/sdtw/barycenter.py -> build/bdist.linux-x86_64/egg/sdtw
copying build/lib.linux-x86_64-2.7/sdtw/__init__.py -> build/bdist.linux-x86_64/egg/sdtw
copying build/lib.linux-x86_64-2.7/sdtw/chainer_func.py -> build/bdist.linux-x86_64/egg/sdtw
copying build/lib.linux-x86_64-2.7/sdtw/setup.py -> build/bdist.linux-x86_64/egg/sdtw
copying build/lib.linux-x86_64-2.7/sdtw/soft_dtw.py -> build/bdist.linux-x86_64/egg/sdtw
byte-compiling build/bdist.linux-x86_64/egg/sdtw/distance.py to distance.pyc
byte-compiling build/bdist.linux-x86_64/egg/sdtw/dataset.py to dataset.pyc
byte-compiling build/bdist.linux-x86_64/egg/sdtw/path.py to path.pyc
byte-compiling build/bdist.linux-x86_64/egg/sdtw/barycenter.py to barycenter.pyc
byte-compiling build/bdist.linux-x86_64/egg/sdtw/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/sdtw/chainer_func.py to chainer_func.pyc
byte-compiling build/bdist.linux-x86_64/egg/sdtw/setup.py to setup.pyc
byte-compiling build/bdist.linux-x86_64/egg/sdtw/soft_dtw.py to soft_dtw.pyc
creating stub loader for sdtw/soft_dtw_fast.so
byte-compiling build/bdist.linux-x86_64/egg/sdtw/soft_dtw_fast.py to soft_dtw_fast.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying soft_dtw.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying soft_dtw.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying soft_dtw.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying soft_dtw.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying soft_dtw.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
creating dist
creating 'dist/soft_dtw-0.1.dev0-py2.7-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing soft_dtw-0.1.dev0-py2.7-linux-x86_64.egg
removing '/usr/local/lib/python2.7/dist-packages/soft_dtw-0.1.dev0-py2.7-linux-x86_64.egg' (and everything under it)
creating /usr/local/lib/python2.7/dist-packages/soft_dtw-0.1.dev0-py2.7-linux-x86_64.egg
Extracting soft_dtw-0.1.dev0-py2.7-linux-x86_64.egg to /usr/local/lib/python2.7/dist-packages
soft-dtw 0.1.dev0 is already the active version in easy-install.pth

Installed /usr/local/lib/python2.7/dist-packages/soft_dtw-0.1.dev0-py2.7-linux-x86_64.egg
Processing dependencies for soft-dtw==0.1.dev0
Finished processing dependencies for soft-dtw==0.1.dev0
```

**Comment by mblondel** [comment]
The installation seems fine. Don't run python from the soft-dtw project root. Once soft-dtw is installed, you need to run it from somewhere else (e.g. from $HOME).

**Comment by Deruijter** [comment]
Mathieu, I fixed my problem after running `make` on the root directory of the project.

I'm not sure if mine is a specific case but it might be worth mentioning in the Installation section of your project. 

Anyway, thanks for your help. I'm really excited to work with your algorithm.

**Comment by mblondel** [comment]
Running `make` alone builds the project inplace and since you added the project to your `PYTHONPATH` this is probably why it's now working. However, running `python setup.py install` should normally work, without changing your `PYTHONPATH`...

**Comment by Deruijter** [comment]
I see. Initially I installed the code as indicated without adding it to my `PYTHONPATH`, however this resulted in non of the modules being found (sdtw was not found for example).

Perhaps this is related to my use of Anaconda, since modules are stored in a specific place if I'm not mistaken.

**Comment by kr11** [comment]
I've tried to launch the python console and run `from sdtw import SoftDTW` at different directories. The root is `soft-dtw`. It's executed successfully in any subfolders of `soft-dtw`, like `soft-dtw/sdtw` and `soft-dtw/dist` and even deeper subfolders, like `soft-dtw/sdtw/tests`, **only except the root directory`soft-dtw`**. Why?
